name: tapapplink_example
description: Minimal example for the tapapplink package.
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"
dependencies:
  flutter:
    sdk: flutter
  tapapplink:
    path: ..
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
