name: tapapplink
description: Tap App Link attribution SDK for Flutter apps.
version: 0.3.1
homepage: https://tapapplink.com
repository: https://github.com/tapapplink/tapapplink-flutter
issue_tracker: https://github.com/tapapplink/tapapplink-flutter/issues
license: MIT
environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.tapapplink.tapapplink
        pluginClass: TapAppLinkPlugin
